services:

  qdrant:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.qdrant
    restart: unless-stopped
    container_name: qdrant
    ports:
      - 6333:6333
    environment:
      - RUN_MODE=${QDRANT_ENV}
    volumes:
      - ./qdrant_data:/qdrant/storage
      - ./qdrant_config.yaml:/qdrant/config/dev.yaml
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:6333/healthz"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  ollama:
    build:
      context: ./dockerfiles
      dockerfile: Dockerfile.ollama
    restart: unless-stopped
    container_name: ollama
    ports:
      - 11434:11434
    environment:
      - EMBEDDING_NAME=${EMBEDDING_NAME}
      - MODEL_NAME=${MODEL_NAME}
    volumes:
      - ./ollama_data:/root/.ollama
    entrypoint: >
      sh -c "
        ollama serve & 
        sleep 5 &&
        ollama pull $EMBEDDING_NAME &&
        ollama pull $MODEL_NAME &&
        pkill -f 'ollama serve'; 
        exec ollama serve
      "
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:11434/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s

  fastapi:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.fastapi
    restart: unless-stopped
    container_name: fastapi-app
    depends_on:
      qdrant:
          condition: service_healthy
      ollama:
          condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - PYTHONUNBUFFERED=1
    healthcheck:
      test: ["CMD", "curl","-f","http://localhost:8000/"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s