FROM python:3.10-slim

RUN apt-get update && apt-get install -y curl

WORKDIR /app

COPY .env /app/

COPY ./code /app/code/

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["uvicorn", "code.main:app", "--host", "0.0.0.0", "--port", "8000"]